export enum KeyboardKey {
  A = "a",
  ArrowDown = "ArrowDown",
  ArrowLeft = "ArrowLeft",
  ArrowRight = "ArrowRight",
  ArrowUp = "ArrowUp",
  Backslash = "\\",
  Backspace = "Backspace",
  C = "c",
  Delete = "Delete",
  Digit1 = "1",
  Digit2 = "2",
  End = "End",
  Enter = "Enter",
  Escape = "Escape",
  F = "f",
  F2 = "F2",
  F5 = "F5",
  Home = "Home",
  P = "p",
  R = "r",
  S = "s",
  T = "t",
  Tab = "Tab",
  V = "v",
  W = "w"
}
