[package]
name = "JumpServerClient"
version = "4.1.2"
description = "JumpServer client tool"
authors = [ "JumpServer" ]
license = "MIT"
repository = "https://github.com/jumpserver/clients"
edition = "2021"

[lib]
name = "jumpserver_client_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies.tauri-build]
version = "2.5.0"
features = [ ]

[dependencies]
url = "2.5.7"
log = "0.4.31"
oauth2 = "5.0.0"
axum = "0.8.9"
keyring = "4.0.1"
keyring-core = "1.0.0"
chrono = "0.4.41"
flate2 = "1.1.5"
font-kit = "0.14"
anyhow = "1.0.100"
serde_json = "1.0"
tar = "0.4"
base64 = "0.22"
fast_image_resize = "6.0"
num_cpus = "1.16"
env_logger = "0.11.8"
tauri-build = "2.5.0"
tauri-plugin-log = "2.8"
tauri-plugin-os = "2.3.1"
tauri-plugin-fs = "2.4.2"
window-vibrancy = "0.7.1"
tauri-plugin-shell = "2.3.1"
tauri-plugin-store = "2.4.0"
tauri-plugin-dialog = "2.7"
tauri-plugin-opener = "2.5.2"
tauri-plugin-notification = "2.3.1"
tauri-plugin-deep-link = "2.4.5"
tauri-plugin-single-instance = "2"
tauri-plugin-clipboard-manager = "2.3.0"
tauri-plugin-prevent-default = "5.0.0"

[dependencies.tokio]
version = "1.46.1"
features = ["rt-multi-thread", "macros", "sync", "time", "net"]

[dependencies.image]
version = "0.25.8"
default-features = false
features = ["png", "jpeg", "webp"]

[dependencies.tauri]
version = "2.11"
features = [
  "macos-private-api",
  "tray-icon",
  "unstable",
]

[dependencies.serde]
version = "1"
features = [ "derive" ]

[dependencies.tauri-plugin-http]
version = "2.5.2"
features = [ "unsafe-headers" ]

[dependencies.reqwest]
version = "0.12.25"
default-features = false
features = [
  "json",
  "native-tls"
]

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "2.9.0"
tauri-plugin-window-state = "2.4.0"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
shiguredo_video_toolbox = { git = "https://github.com/shiguredo/video-toolbox-rs", branch = "develop" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
] }

[target.'cfg(target_os = "linux")'.dependencies]
openh264 = "0.7"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
opt-level = "s"
panic = "abort"
