# Use base image to build the project avoid npm install every time
FROM jumpserver/luna-base:20250609_105214 AS stage-build

ARG VERSION
ENV VERSION=$VERSION

ADD . /data

RUN sed -i "s@version =.*;@version = '${VERSION}';@g" src/environments/environment.prod.ts \
    && yarn build \
    && cp -R src/assets/i18n dist/luna/

FROM scratch
COPY --from=stage-build /data/dist/luna /luna

# docker buildx build -f Dockerfile.build  --output type=tar,dest=./luna.tar.gz,compression=gzip .