minimumReleaseAgeExclude:
  - "@ai-sdk/gateway@4.0.33"
  - "@ai-sdk/provider-utils@5.0.16"
  - "@ai-sdk/vue@4.0.44"
  - ai@7.0.44
shellEmulator: true

overrides:
  "app-builder-lib@26.15.3>@electron/get": 5.1.0
  cpu-features: "-"

packages:
  - .
  - electron
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  electron-winstaller: true
  esbuild: true
  node-pty: true
  ssh2: false
  unrs-resolver: true
  vue-demi: true

patchedDependencies:
  guacamole-common-js-jumpserver@1.1.0-c: patches/guacamole-common-js-jumpserver@1.1.0-c.patch
