minimumReleaseAgeExclude:
  - "@ai-sdk/gateway@4.0.33"
  - "@ai-sdk/provider-utils@5.0.16"
  - "@ai-sdk/vue@4.0.44"
  - ai@7.0.44
shellEmulator: true
nodeLinker: hoisted

overrides:
  "@electron/rebuild": 4.2.0
  cpu-features: "-"

packages:
  - .
  - electron
  - packages/*

allowBuilds:
  "@bitdisaster/exe-icon-extractor": true
  "@parcel/watcher": true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  node-pty: true
  ssh2: false
  unrs-resolver: true
  vue-demi: true

patchedDependencies:
  guacamole-common-js-jumpserver@1.1.0-c: >-
    patches/guacamole-common-js-jumpserver@1.1.0-c.patch
