
minimumReleaseAgeExclude:
  - "@ai-sdk/gateway@4.0.33"
  - "@ai-sdk/provider-utils@5.0.16"
  - "@ai-sdk/vue@4.0.44"
  - ai@7.0.44
shellEmulator: true

packages:
  - .
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

