pub struct MenuLabels {
    pub about_label: String,
    pub settings_label: String,
    pub file_label: String,
    pub edit_label: String,
    pub view_label: String,
    pub window_label: String,
    pub help_label: String,
    pub undo_label: String,
    pub redo_label: String,
    pub cut_label: String,
    pub copy_label: String,
    pub paste_label: String,
    pub select_all_label: String,
    pub focus_mode_label: String,
    pub left_panel_label: String,
    pub right_panel_label: String,
    pub batch_command_label: String,
    pub close_label: String,
    pub minimize_label: String,
    pub maximize_label: String,
    pub fullscreen_label: String,
    pub hide_label: String,
    pub hide_others_label: String,
    pub show_all_label: String,
    pub quit_label: String,
}

pub fn menu_labels(use_zh: bool, app_name: &str) -> MenuLabels {
    if use_zh {
        MenuLabels {
            about_label: format!("关于 {app_name}"),
            settings_label: "设置".into(),
            file_label: "文件".into(),
            edit_label: "编辑".into(),
            view_label: "视图".into(),
            window_label: "窗口".into(),
            help_label: "帮助".into(),
            undo_label: "撤销".into(),
            redo_label: "重做".into(),
            cut_label: "剪切".into(),
            copy_label: "复制".into(),
            paste_label: "粘贴".into(),
            select_all_label: "全选".into(),
            focus_mode_label: "纯净模式".into(),
            left_panel_label: "左侧面板".into(),
            right_panel_label: "右侧面板".into(),
            batch_command_label: "批量命令".into(),
            close_label: "关闭窗口".into(),
            minimize_label: "最小化窗口".into(),
            maximize_label: "缩放".into(),
            fullscreen_label: "进入全屏幕".into(),
            hide_label: format!("隐藏 {app_name}"),
            hide_others_label: "隐藏 其他窗口".into(),
            show_all_label: "显示所有窗口".into(),
            quit_label: "退出".into(),
        }
    } else {
        MenuLabels {
            about_label: format!("About {app_name}"),
            settings_label: "Settings".into(),
            file_label: "File".into(),
            edit_label: "Edit".into(),
            view_label: "View".into(),
            window_label: "Window".into(),
            help_label: "Help".into(),
            undo_label: "Undo".into(),
            redo_label: "Redo".into(),
            cut_label: "Cut".into(),
            copy_label: "Copy".into(),
            paste_label: "Paste".into(),
            select_all_label: "Select All".into(),
            focus_mode_label: "Focus Mode".into(),
            left_panel_label: "Left Panel".into(),
            right_panel_label: "Right Panel".into(),
            batch_command_label: "Batch Command".into(),
            close_label: "Close Window".into(),
            minimize_label: "Minimize Window".into(),
            maximize_label: "Zoom".into(),
            fullscreen_label: "Enter Full Screen".into(),
            hide_label: format!("Hide {app_name}"),
            hide_others_label: "Hide Others".into(),
            show_all_label: "Show All".into(),
            quit_label: "Quit".into(),
        }
    }
}
