export enum FORMATTER_MESSAGE_TYPE {
  PING = "PING",
  TERMINAL_INIT = "TERMINAL_INIT",
  TERMINAL_DATA = "TERMINAL_DATA",
  TERMINAL_SHARE = "TERMINAL_SHARE",
  TERMINAL_RESIZE = "TERMINAL_RESIZE",
  TERMINAL_SHARE_USER_REMOVE = "TERMINAL_SHARE_USER_REMOVE",
  TERMINAL_GET_SHARE_USER = "TERMINAL_GET_SHARE_USER"
}

export enum ZMODEM_ACTION_TYPE {
  ZMODEM_START = "ZMODEM_START",
  ZMODEM_END = "ZMODEM_END",
  ZMODEM_ABORT = "ZMODEM_ABORT"
}

export enum MESSAGE_TYPE {
  PING = "PING",
  CLOSE = "CLOSE",
  ERROR = "ERROR",
  CONNECT = "CONNECT",
  TERMINAL_SHARE = "TERMINAL_SHARE",
  TERMINAL_ERROR = "TERMINAL_ERROR",
  MESSAGE_NOTIFY = "MESSAGE_NOTIFY",
  TERMINAL_ACTION = "TERMINAL_ACTION",
  TERMINAL_SESSION = "TERMINAL_SESSION",
  TERMINAL_READY = "TERMINAL_READY",
  TERMINAL_PERM_VALID = "TERMINAL_PERM_VALID",
  TERMINAL_SHARE_JOIN = "TERMINAL_SHARE_JOIN",
  TERMINAL_SHARE_LEAVE = "TERMINAL_SHARE_LEAVE",
  TERMINAL_PERM_EXPIRED = "TERMINAL_PERM_EXPIRED",
  TERMINAL_SESSION_PAUSE = "TERMINAL_SESSION_PAUSE",
  TERMINAL_SESSION_RESUME = "TERMINAL_SESSION_RESUME",
  TERMINAL_GET_SHARE_USER = "TERMINAL_GET_SHARE_USER",
  TERMINAL_SHARE_USER_REMOVE = "TERMINAL_SHARE_USER_REMOVE"
}

export enum HOST_MESSAGE_TYPE {
  PING = "PING",
  PONG = "PONG",
  CMD = "CMD",
  FOCUS = "FOCUS",
  OPEN = "OPEN",
  CREATE_FILE_CONNECT_TOKEN = "CREATE_FILE_CONNECT_TOKEN",
  GET_FILE_CONNECT_TOKEN = "GET_FILE_CONNECT_TOKEN",
  TERMINAL_THEME_CHANGE = "TERMINAL_THEME_CHANGE",
  CLOSE = "CLOSE",
  TERMINAL_ERROR = "TERMINAL_ERROR",
  SHARE_CODE_RESPONSE = "SHARE_CODE_RESPONSE",
  SHARE_USER_ADD = "SHARE_USER_ADD",
  SHARE_USER_LEAVE = "SHARE_USER_LEAVE",
  KEYEVENT = "KEYEVENT",
  TERMINAL_CONTENT = "TERMINAL_CONTENT_REQUEST",
  TERMINAL_CONTENT_RESPONSE = "TERMINAL_CONTENT_RESPONSE",
  CLICK = "CLICK",
  INPUT_ACTIVE = "INPUT_ACTIVE"
}
