[package]
name = "jump-server-client"
version = "1.4.0"
description = "JumpServer client tool"
authors = [ "ZhaoJiSen" ]
license = "MIT"
repository = "https://github.com/jumpserver/clients"
edition = "2021"

[lib]
name = "jump_server_client_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies.tauri-build]
version = "2.3.0"
features = [ ]

[dependencies]
log = "0.4.27"
env_logger = "0.11.8"
url = "2.5.7"
tauri-plugin-shell = "2.3.0"
tauri-plugin-notification = "2.3.0"
tauri-plugin-os = "2.3.0"
tauri-plugin-fs = "2.4.0"
tauri-plugin-store = "2.3.0"
window-vibrancy = "0.6.0"
tauri-build = "2.4.0"
tokio = "1.46.1"

[dependencies.tauri]
version = "2.6.2"
features = [
  "macos-private-api",
  "tray-icon",
  "unstable",
]

[dependencies.serde]
version = "1"
features = [ "derive" ]

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-window-state = "2.4.0"
